version: '3.3'

services:
    integration-db:
      image: postgres:14.1
      restart: always
      networks:
        - database
      environment:
        POSTGRES_PASSWORD: psql
        POSTGRES_USER: postgres
        POSTGRES_DB: Hospital
      volumes:
        - type: bind
          source: ./init.sql
          target: /docker-entrypoint-initdb.d/init.sql
      ports:
        - 5432:5432

networks:
    database:
      name: database
      driver: bridge