CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Pharmacy" (
    "IdPharmacy" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "NamePharmacy" text NULL,
    "ApiKeyPharmacy" text NULL,
    "Endpoint" text NULL,
    "Address" text NULL,
    "City" text NULL,
    "Contact" text NULL,
    "Email" text NULL,
    "Notes" text NULL,
    CONSTRAINT "PK_Pharmacy" PRIMARY KEY ("IdPharmacy")
);

CREATE TABLE "Prescriptions" (
    "IdPrescription" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Patient" text NULL,
    "PatientJMBG" text NULL,
    "Doctor" text NULL,
    "MedicineId" integer NOT NULL,
    "DurationInDays" integer NOT NULL,
    "TimesPerDay" integer NOT NULL,
    "Description" text NULL,
    CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("IdPrescription")
);

CREATE TABLE "Response" (
    "IdFeedback" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdPharmacy" integer NOT NULL,
    "ContentFeedback" text NOT NULL,
    CONSTRAINT "PK_Response" PRIMARY KEY ("IdFeedback")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211213164525_PrescriptionMigration2', '3.1.20');

